### ISSUE TITLE
Can I used this pipeline for non-human species？

### ISSUE THREAD

**Issue by silvewheat** [genxnetwork/grape#90]
Hi,
I want to build pedigree from livestock genomic data. Is this pipeline support non-human reference genomes?

Best,
Yudong

**Comment by Jahysama** [comment]
Hello, Cai!
Unfortunately in your case, only the `find` workflow would work, because GRAPE preprocess flow uses MAF and alleles from 1000G human dataset. So you need to preprocess data on your own.
At the end for the Relatedness Inference pipeline, you would need:
```
data.vcf.gz - if you are using GERMLINE+ERSA it needs to be phased, leave it unphased if using any other flow.
data.bed        |
data.fam        | - this 3 plink files emerge directly from data.vcf.gz by using plink --make-bed
data.bim        |
data_mapped.bim - this file needs to be created for any flow that includes IBIS using the corresponding map file. For more info check out https://github.com/williamslab/ibis "Steps for running IBIS" section in README.md
```
For meaningful results your `data.vcf.gz` should be with MAF below 0.02 and missing frequency below 15%.
You also need to structure your working_dir as follows:
```
working_dir
└── preprocessed
    ├── data.bed
    ├── data.bim
    ├── data.fam
    ├── data_mapped.bim
    └── data.vcf.gz

**Comment by ruslanvakhitov** [comment]
issue closed
